language: rust

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add clippy-preview
script:
  - cargo clippy
  - cargo test

cache:
  cargo: true
  directories:
    - target
